name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  build-rust:
    name: Build Rust package
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rust package
        run: cargo package

  build-python:
    name: Build Python package
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up `uv`
        uses: astral-sh/setup-uv@v6

      - name: Build Python distribution
        run: uv build

      - name: Upload Python distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs:
      - build-rust
      - build-python
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # `actions/checkout@v4` somehow transforms annotated tags into
      # lightweight tags, which prevents us from reading release notes.
      # This fetches annotated tags and overrides existing mangled tags.
      - name: Fetch annotated tags
        run: git fetch --tags --force

      - name: Extract tag annotation
        id: tag
        run: |
          title=$(git tag -l --format='%(contents:subject)' ${{ github.ref_name }})
          body=$(git tag -l --format='%(contents:body)' ${{ github.ref_name }})
          echo "title=$title" >> $GITHUB_OUTPUT
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.tag.outputs.title }}
          body: ${{ steps.tag.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-crate:
    name: Publish crate
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  publish-pypi:
    name: Publish Python package
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download Python distribution
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Publish Python package
        uses: pypa/gh-action-pypi-publish@release/v1
